CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       done BOOLEAN NOT NULL,
                       createdAt TIMESTAMP NOT NULL,
                       owner_id BIGINT NOT NULL,
                       CONSTRAINT fk_tasks_owner
                           FOREIGN KEY (owner_id)
                               REFERENCES users(id)
);
