CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       title VARCHAR(255) NOT NULL,
                       done BOOLEAN NOT NULL DEFAULT FALSE,
                       created_at TIMESTAMP NOT NULL,

                       owner_id BIGINT NOT NULL,

                       CONSTRAINT fk_tasks_owner
                           FOREIGN KEY (owner_id)
                               REFERENCES users (id)
);
